<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  'Access denied by cochanges\\frontend\\modules\\auth\\controllers\\ValidateController' => '',
  'Code has expired. {a}Send the code again{/a}' => '',
  'Code re-sent ' => '',
  'Code sent ' => '',
  'Confirmation code for {siteName} ' => '',
  'If you are asked not to send you the code, please ignore the letter. ' => '',
  'Please enter your e-mail' => '',
  'SMS delivery is failed' => '',
  'The code can not be issued earlier than 3 minutes from the time of dispatch of the previous' => '',
  'There were one or more errors in your submission. Please correct the marked fields below.' => '',
  'This email address already exists. Please log In if you already registered' => '',
  'This phone number already exists' => '',
  'This user is blocked' => '',
  'We send you a verification code. A one-time code, your password has not changed. After entering the verification code, you can change your password in your profile. ' => '',
  'You must accept terms and conditions' => '',
  'Your code: ' => '',
  'Your confirmation code has been sent to your email address' => '',
  'Your password on {siteName} ' => '',
  'thank you with us again! ' => '',
  'will send you a confirmation code ' => '',
  ' use:' => ' usi:',
  ' welcome to {siteName}!' => 'benvingut(a) a {siteName}!',
  'If you forgot your password, you can enter a new one. ' => 'Si has oblidat la teva contrassenya, pots introduïr-ne una de nova.',
  'If you haven’t requested a password change, we’re sorry to disturb you, and just ignore this letter.' => 'Si no has sol·licitat un canvi de contrassenya, disculpa la molèstia i ignora aquest correu.',
  'Incorrect code' => 'Codi incorrecte',
  'Incorrect e-mail.Please, enter a correct e-mail address.' => 'Correu electrònic incorrecte. Si us plau, introdueix un correu electrònic vàlid',
  'Login:' => 'Login:',
  'Oops, something went wrong. Please, try again' => 'Vaja! Quelcom ha anat malament. Intenta-ho novament si us plau.',
  'Oops, something went wrong. Please, try again.' => 'Vaja! Quelcom ha anat malament. Intenta-ho novament si us plau.',
  'Oops, something went wrong. Please, try again."' => 'Vaja! Quelcom ha anat malament. Intenta-ho novament si us plau."',
  'Oops, something went wrong. Send the code again' => 'Vaja! Quelcom ha anat malament. Envia el codi de nou si us plau.',
  'Oops, something went wrong. Send the code again?' => 'Vaja! Quelcom ha anat malament. Enviar el codi de nou?',
  'Password from the e-mail' => 'Contrassenya del correu electrònic',
  'Password:' => 'Contrassenya:',
  'Please choose a profile' => 'Si us plau, escull un perfil',
  'Please choose a region from the list' => 'Si us plau, escull una regió de la llista',
  'Please, fill in' => 'Si us plau, ompla aquest camp',
  'Please, go to the link:' => 'Si us plau, ves a:',
  'Thanks! Password reset instructions were sent to your e-mail.' => 'Gràcies! T’hem enviat les instruccions per correu electrònic per a recuperar la contrassenya.',
  'The password doesn’t match. If you can’t remember the password, press "Change the Password"' => 'La contrassenya no coincideix. Si no recordse la teva contrassenya, fes click a "Canviar la contrassenya"',
  'There is no such e-mail address in our base. Please, sign up' => 'No tenim aquest correu electrònic a la nostra base de dades. Si us plau, crea un compte',
  'To log in to ' => 'Per a iniciar sessió a ',
  'You may change the password after' => 'Pots canviar la contrassenya després del',
  'Your account is created. To log in, enter the password sent to your e-mail' => 'T’has registrat amb èxit. Per a iniciar sessió, introdueix la contrassenya proporcionada per correu electrònic',
  'You’ve signed up to {siteName}' => 'T’has registrat a {siteName}',
  'did you forget your password?' => 'Has oblidat la contrassenya?',
  'logging in on' => 'sessió iniciada a',
);
