<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  '- Create groups and participate in {br /}' => '',
  '- To collect and give money to socially useful projects and actions {br /} ' => '',
  '- To create excuses, handling, voting events {br /}' => '',
  'After confirmation, you will discover many new features on {siteName}. You`ll be able to: {br /}' => '',
  'After confirmation, you will discover many new features to the project {siteName} ' => '',
  'Code is in SMS' => '',
  'Confirm your phone number' => '',
  'Confirmation code ' => '',
  'Do you really want to make this account primary? ' => '',
  'Image size not more than 5MB. ' => '',
  'No, thanks' => '',
  'Select the account under which you want to use {siteName}' => '',
  'Send confirmation code' => '',
  'There was an error loading the image. ' => '',
  'You are logged in as' => '',
  'Your profile picture' => '',
  ' - social initiative support platform' => ' - plataforma de suport a inciatives socials',
  ' The file extension jpg | jpeg | png | tiff | gif.' => ' Format d’arxiu jpg | jpeg | png | tiff | gif',
  ' develops a participatory society, involving locals in changing what`s around them. The platform helps to make life better in a particular courtyard, district and a whole city.' => ' desenvolupa un societat de participació, que inclou els residents en la transformació de l’ambient. La plataforma ajuda a millorar la vida al pati, al barri o a tota la ciutat.',
  'A server error occurred, please try later.' => 'Ha ocorregut un error al servidor. Si us plau, intenta-ho més tard.',
  'Add' => 'Afegir',
  'Cancel' => 'Cancel·lar',
  'Change the password' => 'Canviar la contrasenya',
  'Create an account' => 'Crear una conta',
  'Enter the e-mail address provided during the registration, and press "Change the Password". We’ll send you a new password.' => 'Introdueix el correu electrònic utilitzat durant el registre i prem a "Canviar la contrasenya". T’enviarem una nova contrasenya.',
  'False' => 'Fals',
  'I accept {userAgreementLink}the terms of use{/userAgreementLink}, agree with processing my personal data and confirm that I am 18.' => 'Accepto els {userAgreementLink}termes d’ús{/userAgreementLink}, el tractament de les meves dades personals i confirmo que tinc 18 anys.',
  'Inhabited locality`s name' => 'Nom de la localitat',
  'Log in' => 'Iniciar sessió',
  'Log out' => 'Sortir',
  'Or sign in through your social network profile' => 'O entra amb el perfil de les teves xarxes socials',
  'Registration' => 'Registre',
  'Remember' => 'Recordar',
  'Reset the password with a phone number' => 'Recuperar la contrasenya amb un número de telèfon',
  'Settings' => 'Configuració',
  'True' => 'Cert',
  'Upload another photo' => 'Carrega un altre foto',
  'Yes' => 'Sí',
  'Your e-mail address' => 'El teu correu electrònic',
  'Your e-mail address or phone number' => 'El teu correu electrònic o número de telèfon',
  'Your name' => 'El teu nom',
  'Your password' => 'La teva contrasenya',
  'Your phone number' => 'El teu número de telèfon',
  'Your surname' => 'El teu cognom',
  'add' => 'afegir',
  'confirm' => 'confirmar',
  'done' => 'fet',
  'log in' => 'iniciar sessió',
  'save' => 'guardar',
  'Continue' => 'Continuar',
);
