<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'City: ' => '',
  'Contact phone: ' => '',
  'Lock business profile on {siteName} ' => '',
  '"{name} ({link})" profile`s administrator designated you as {position}.' => 'L’administrador del perfil "{name} ({link})" el va designar {position}.',
  'E-mail: ' => 'Correu electrònic: ',
  'If you have questions or proposals, contact us: {support_email}
This letter was sent automatically, don`t reply. ' => 'Si té preguntes o propostes, poseu-vos en contacte amb nosaltres: {support_email}
Aquesta carta es va enviar automàticament, no la respongui. ',
  'Kind regards, ' => 'Atentament, ',
  'Name: ' => 'Nom: ',
  'Show more' => 'Mostrar més',
  'Subscribe' => 'Subscriure',
  'Unsubscribe' => 'Cancel',
  'Volunteer`s questionnaire on {siteName}' => 'Qüestionari del voluntari a {SITENAME}',
  '{siteName}: you are listed as "{businessprofile}" employee' => '{SITENAME}: notificació sobre la subscripció al perfil de negoci "{businessprofile}"',
);
