<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A server error occurred. Try again later.' => 'S’ha produït un error al servidor. Torna-ho a provar més tard.',
  'Close the promo pack and not show it in the profile.' => 'Tanqui el paquet promocional i no el veurà en el seu perfil',
  'Edit' => 'Editar',
  'Oops! The photo should be not smaller than 800x600 and not smaller than 15Mb. File`s format: jpg | jpeg | png | tiff | gif.' => '¡Huy! La foto ha de ser no menor de 800x600 i no menor de 15Mb. El format de l’archivo: jpg | jpeg | png | tiff | gif.',
  'The photo should be not smaller than 800x600 and not smaller than 15Mb.' => 'La foto ha de ser no menor de 800x600 i no menor de 15Mb.',
  'Upload a background image' => 'Pujar una imatge de fons ',
  'Upload another photo (not bigger than 15 MB, not smaller than 800x600).' => 'Pujar una altra  foto (no més de 15 Mb, no menys de 800x600).',
  'cancel' => 'cancelar',
  'open the promo pack' => 'obrir el promo pack',
  'save' => 'guardar',
  'upload your' => 'Carregar la seva',
);
