<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Your {entityNameTxt} on {siteName} commented on ' => '',
  'comment deleted' => '',
  ' ' => ' ',
  'COMMENTS' => 'COMENTARIS',
  'Cancel' => 'Cancel·lar',
  'Comment' => 'Сomentari',
  'Reply' => 'Respondre',
  'Save' => 'Guardar',
  'You have an answer to your comment on {siteName} ' => 'Tens una resposta al teu comentari a {siteName}',
  'Your contribution to {siteName} has received a new comment' => 'La teva contribució a {siteName} ha rebut un comentari nou',
  'all comments' => 'tots els comentaris',
  'commented on' => 'comentat',
  'comment|comments' => 'comentari|comentaris',
  'on' => 'a',
  'replied' => 'respondre',
  'to your comment in' => 'al seu comentari a',
  'userpic' => 'imatge de perfil',
  '{n} answer|{n} answers|{n} answers' => '{n} resposta|{n} respostes|{n} respostes',
);
