<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Edit Poll ' => '',
  'Edit appeal ' => '',
  'Edit event ' => '',
  'Edit link' => '',
  'Edit pretext ' => '',
  'Mode ' => '',
  'Through fasting ID ' => '',
  'Comments' => 'Сomentaris',
  'Creation date' => 'Data de creació',
  'Edit the action' => 'Editar l’acció',
  'Edit the profile' => 'Editar el perfil',
  'Group ' => 'Grup',
  'Latitude' => 'Latitud',
  'Life sphere' => 'Tema',
  'Longitude' => 'Longitud',
  'Organization' => 'Organizació',
  'Region' => 'Regió',
  'Status' => 'Estat',
  'Status in the group' => 'Estat en el grup',
  'Supplementary status in the group' => 'Estat addicional en el grup',
  'User' => 'Usuari',
  'Venue' => 'Lloc',
);
