<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Anonymous user' => '',
  'To register, click on "Give money"' => '',
  'collected' => '',
  'collected of {n}' => '',
  'After fulfillment of your promise,{br /}share the results with everyone' => 'Un cop complerta la promesa, {br /} comparteix els resultats amb tothom',
  'Choose an action' => 'Escull una acció',
  'Crowdfunding is finished' => 'Finançaments col·lectius s’ha completat',
  'The donated amount will leave your account each month during the donation period' => 'La quantitat donada serà transferida del teu compte cada mes durant el període de donació',
  'Crowdfunding is over<br>The target sum wasn`t collected' => 'Crowdfunding s’ha acabat<br>No s’ha arribat a l’objectiu',
  'Donate' => 'Donar',
  'It`s done!' => 'Fet!',
  'The action is canceled' => 'L’acció s’ha cancel·lat',
  'The action<br /> is failed' => 'L’acció <br /> s’ha acabat',
  'The action<br /> is stopped.' => 'L’acció <br /> s’ha aturat.',
  'The organizator will have {n} days to use the money by purpose.' => 'L’organitzador tindrà {n} dies per a emprar els diners en l’objetiu previst',
  'The promise <br /> is fulfilled' => 'La promesa  <br /> s’ha cumplert',
  'The promise <br /> isn`t fulfilled' => 'La promesa <br /> no  s’ha cumplert',
  'The report template with further instructionswill be sent to your{tag}{email}{/tag}.' => 'La plantilla de l’informe de resultats amb les instruccions següents s’enviaran al teu correu electrònic {tag}{email}{/tag}.',
  'The time for fulfillment has passed{br /}The promise wasn`t fulfilled' => 'Ha expirat el plaç{br /}La promesa no s’ha cumplert',
  'Time for fulfillment' => 'Temps restant',
  'Time for fulfillment has passed. Nothing is done.' => 'Ha expirat el plaç. No s’ha fet res.',
  'To choose an action you have' => 'Per escullir una acció has de ',
  'Until the end' => 'Fins al final',
  'Yay! The money is collected!' => 'Guai! S’han captat tots els diners!',
  'You donated ' => 'Has donat ',
  'You transferred to the action' => 'Has transferit l’acció',
  'You`ll have {n} days to use the money by purpose' => 'Tindras {n} dies per emprar els diners en l’objetiu previst',
  'collected {collected}' => 'captat {collected}',
  'or you can {tag}cancel the action{/tag}' => 'o pots {tag}cancel·lar l’acció{/tag}',
  'reports' => 'informes',
  'the action didn`t raise enough funds, but you can transfer your money to other action.' => 'l’acció no ha recullit suficients fons, però pots transferir els teus diners a una altra acció.',
  'until the end' => 'fins al final',
  'you donated ' => 'has donat ',
  'your supporters are waiting! fulfill your promises and share the story!' => 'la gent que ha confiat en tu vol notícies! Cumpleix la teva promesa i comparteix la història',
  '{n} days left' => 'queden {n} dies',
  '{n} person | {n} people' => '{n} persones',
  '{n}day left |{n} days left | {n} days left ' => 'queda {n} dia | queden {n} dies | queden {n} dies ',
  '{tag}{collected}{/tag} out of {total}' => '{tag}{collected}{/tag} de {total}',
  '{tag}{collected}{/tag}{br /} collected' => '{tag}{collected}{/tag}{br /} captat',
);
