<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'after' => '',
  'less than a minute' => '',
  'today in {time}' => '',
  '{n} hour|{n} hours' => '',
  '{n} minute|{n} minutes' => '',
  'just now' => 'ara mateix',
  'the day before yesterday at {time}' => 'abans d’ahir a les {time}',
  'yesterday at {time}' => 'ahir a les {time}',
  '{n} day|{n} days' => '{n} dia que es queda|{n} dies que es queden',
  '{n} hour ago | {n} hours ago' => 'fa {n} hora | fa {n} hores',
  '{n} minute ago|{n} minutes ago' => 'fa {n} minut|fa {n} minuts',
);
