<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Unknown parent entity' => '',
    'post' => '',
    'Уважаемая {name}' => '',
    'Уважаемый {name}' => '',
    'Dear {name}' => 'Benvolgut/da {name}',
    'Dear {name},' => 'Benvolgut/da {name},',
    'crowdfunding' => 'finançaments col·lectius',
    'event' => 'esdeveniment',
    'issue' => 'assumpte',
    'petition' => 'peticion',
    'poll' => 'votació',
    'your crowdfunding' => 'el seu crowdfunding',
    'your event' => 'el seu esdeveniment',
    'your issue' => 'el seu assumpte',
    'your petition' => 'la seva petició',
    'your poll' => 'la seva votació',
    'your post' => 'la seva publicació',
    'Your contribution to' => 'La seva contribució a',
    'commented on' => 'ha rebut un comentari',
);
