<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Administrator will be removed' => '',
  'Become an expert' => '',
  'Expert will be removed' => '',
  'I agree to become an expert on the Internet platform {siteName}' => '',
  'I agree to join the project team on {siteName}' => '',
  'Permission granted to create my account and accept the rules of {tag}site{/tag}.' => '',
  'Please tell the author the reason why:' => '',
  'User will be deleted from the project' => '',
  'User will be removed' => '',
  'Want to join in the project {siteName} and develop the city along with all?' => '',
  'Why I don\'t want to join the team' => '',
  'Why I won\'t be an expert' => '',
  'Your refusal was sent to the author of the project.' => '',
  'Add' => 'Añadir',
  'Administrator' => 'Administrador',
  'Confirm' => 'Confirmar',
  'Continue' => 'Continuar',
  'E-mail' => 'Correu electrònico',
  'E-mail or ID' => 'Correu electrònico o ID',
  'Expert' => 'Expert',
  'Expert opinion' => 'Opinió d’expert',
  'Form your project`s team, attract experts and administrators' => 'Formi el seu equip de projecte i atregui a experts i administradors',
  'In the project' => 'Al projecte',
  'Invitation{br /}sent' => 'La invitació{br /}ha estat enviada',
  'Invite' => 'Invitar',
  'Invited person`s name' => 'Nom de la persona invitada',
  'Invited person`s surname' => 'Cognom de la persona invitada',
  'Join' => 'Unir-se',
  'Join project`s team on {siteName}' => 'Unir-se a l’equip del projecte a {siteName}',
  'Name Surname' => 'Nom Cognom',
  'No' => 'No',
  'Not found' => 'No s`ha trobat',
  'Refuse' => 'Rebutjar',
  'Send' => 'Enviar',
  'Subscribe' => 'Subscriure’s',
  'The invitation {br /} wasn`t accepted.' => 'La invitació {br /} no ha estat acceptada.',
  'The page was not found' => 'La pàgina no s’ha trobat',
  'Unsubscribe' => 'Cancel·lar',
  'Yes' => 'Si',
  'administrator' => 'administrador',
  'expert' => 'expert',
  'invite' => 'convidar',
  'press here to add an' => 'premi per afegir un',
);
