<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'For authorities {tag} is a convenient tool of interaction with the citizens and feedback. {tag} involves citizens in social life and lets them participate in polls while assigning budget funds.' => '{tag} es una eina d’interacció convenient tan per les Autoritats com pels ciutadans. {tag} involucra als ciutadans en la vida pública permetent-los participar en enquestes, donar la seva opinió i participar en la distribució de les partides pressupostaries.',
  'If you have any questions or problems with the site, contact our helpdesk: ' => 'Si te algún dubte, incidència o preguntes sobre el funcionament del lloc, si us plau, posi’s en contacte amb el nostre servei de suport tècnic.',
  'Thanks to {tag}, NGOs and public organizations get support from mass media, and the commercial organizations use {tag} for promoting brand’s social image and communicating with the audience.' => 'Gràcies a {tag}, les organitzacions públiques obtenen ecolzament de RRPP dels mitjans de comunicació, i el negoci utilitza {tag} per a promoure la imatge social de la marca y comunicar-se amb l’auditori.',
  'For cooperation, contact us: ' => ' Per qüestions de cooperació, si us plau, escrigui a',
  'What is ' => '¿Què es ',
  ' is a local web project  offering user-friendly technologies of participation and interaction.' => ' – es una plataforma real que ofereix tecnologies per a la participació i interacció.',
  '{tag} lets the city’s activists involve a great number of people in different initiatives and find like-minded people. Our lawyers help to make appeals to authorities and control their execution. Also crowdfunding actions may be held on {tag}.' => '{tag} permet als activistes de la ciutat involucrar a mes ciutadans en diverses iniciatives i crear comunitats. Els nostres advocats ajuden a escriure sol·licituts a les autoritats i a fer-ne seguiment de l’execuxió. També s’hi poden organitzar accions de micromecenatge a {tag}.',
  'People living nearby and having similar interests use {tag} for solving common problems and making your city, area or yard better. Thanks to {tag} services, it is very easy to participate in the city’s life. You can change something just with one click without leaving your coach.' => 'Els conciutadans amb interessos comuns utilitzen {tag} per a donar sol·lució a problemes comuns y realitzar idees de millora a nivell de ciutat, barri o pati. Gràcies als serveis de {tag}, es molt mes fàcil participar en la vida de la ciutat ja que podem canvia coses amb un simple click assegut al sofà de casa.',
);
