<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Currently there are no events' => '',
  'Find and invite neighbors' => '',
  'Or join in order to be informed of the place' => '',
  'Add a photo' => 'Adjuntar una foto',
  'Add a rule' => 'Afegir una regla',
  'Add your life rule' => 'Afegeixi la seva regla de vida',
  'An error has occurred.' => 'S’ha produït un error.',
  'An error has occurred. Image size not more than 15MB. The file extension jpg | jpeg | png | tiff | gif.' => 'S’ha produït un error. L’arxiu no ha de ser més gran de 15 Mb. El format de l’arxiu jpg | jpeg | png | tiff | gif.',
  'Become the first' => 'Sigui el primer',
  'Invitation sent!' => 'La invitació ha estat enviada',
  'Join' => 'Unir-se',
  'Leave' => 'Deixar',
  'No residents yet' => 'Encara no hi han residents',
  'No rules yet' => 'Encara no hi han regles.',
  'Place’s rating' => 'Classificació del lloc',
  'Something to share about this place?' => 'Té quelcom que compartir sobre aquest lloc?',
  'Start typing the address of your home, workplace or school' => 'Empiece a escribir la dirección de su casa, lugar de trabajo o escuela’ Comenci a escriure l’adreça de casa seva, lloc de feina o escola',
  'There`s no photo.' => 'No hi ha cap foto.',
  'add' => 'afegir',
  'change the address' => 'canviar l’adreça',
  'events' => 'events',
  'life rules' => 'regles de vida',
  'photo' => 'foto',
  'residents' => 'residents',
);
