<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Places{tag} nearby' => '',
  'Delete' => 'Eliminar',
  'Delete the name' => 'Eliminar el nom',
  'Give a name to this point' => 'Donar un nom a aquest punt',
  'Place|Places|Places' => 'Lloc|Llocs|Llocs',
  'Remove&nbsp;your&nbsp;name' => 'Eliminar el nom',
  'Specify the street, the building' => 'Especificar el carrer, l’edifici',
  'Start typing the address or<br />specify the place on the map' => 'Comenci a escriure l’adreça o <br />especifiqui un lloc en el mapa',
  'or mark it on the map' => 'o marcar-la al mapa',
);
