<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Contacting authorities' => '',
  'Learn from the residents' => '',
  'Share news, idea, opinion or share issue' => '',
  'Sponsoring' => '',
  'Album' => 'Àlbum',
  'Collecting signatures to solve the problem' => 'Recollint de signatures per resoldre el problema',
  'Copy the link and paste it here' => 'Copia l’enllaç i enganxa’l aquí',
  'Crowdfunding' => 'Crowdfunding',
  'Description' => 'Descripció',
  'End date' => 'Data de finalització',
  'Event' => 'Event',
  'Event’s starting time' => 'Hora d’inicio de l’event',
  'Invite residents to participate' => 'Invita als ciutadans a participar.',
  'Is voting allowed?' => 'Es pot votar?',
  'Issue' => 'Assumpte',
  'Link' => 'Enllaç',
  'Link to the source' => 'Enllaç a la font',
  'Petition' => 'Sol·licitud',
  'Poll' => 'Vots',
  'Project name' => 'Nom del projecte',
  'Question' => 'Pregunta',
  'Source`s author' => 'Autor de la font',
  'Source`s name' => 'Nom de la font',
  'Start date' => 'Data d’inici',
  'Title' => 'Títol',
  'To' => 'A',
  'To the project on making the city better' => 'Projecte per millorar la ciutat.',
  'Total' => 'Total',
  'more' => 'més',
);
