<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'An invitation to an online broadcast of the new project Maxim Nogotkov' => '',
  'Before the event: ' => '',
  'Enter your email if you do not have an invitation.' => '',
  'Get prompt ' => '',
  'Please make sure your e-mail ' => '',
  'The future will be? ' => '',
  'The project is a tool to bring together concerned citizens, to improve life in our country with the help of real action. We want to give everyone the opportunity to influence the policy of the state, repeatedly increasing the power of your voice. We believe in each initiative and the ability of people to contribute to the development of their region, town, country. ' => '',
  'We create a politically neutral online platform and invite everyone, regardless of the views and beliefs, to use it for the realization of their objectives in the development of our society. ' => '',
  'You &mdash; is power ' => '',
  'За дополнительной информацией вы можете обратиться{br /}к Шулаковой Наталье — +7 (916) 060-60-91' => '',
  'Президент ГК «Связной» Максим Ноготков приглашает вас принять участие в открытии своего нового проекта в сфере гражданских инициатив и электронной демократии. Онлайн-трансляция запуска начнется 22 ноября в 11:15 по московскому времени.' => '',
  'About' => 'Sobre el projecte',
  'E-mail' => 'Correu electrònic',
  'Feedback' => 'La seva opinió',
  'Help' => 'Ajuda',
  'Please indicate the e-mail address' => 'S’ha d’introduir el correu electrònic',
  'Please verify the spelling of the e-mail address (no MX record)' => 'Comprovi la correció del correu electrònic (no hi ha registre de Mail eXchanger)',
  'Privacy' => 'Privacitat',
  'The invitation is sent!' => 'L’invitació s’ha enviat',
  'This e-mail address is incorrect' => 'Correu electrònic incorrecte',
  'This e-mail address is too long' => 'El correu electrònic es massa llarg',
);
