<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'After confirming your support, you will become a user of the system {tag}, and your opinion will be reflected on the page treatment and collective letters to be forwarded to the public authorities. ' => '',
  'Collective petition forwarded {department} ' => '',
  'Confirm treatment support ' => '',
  'E-Mail' => '',
  'For authorization in the system {tag} use the following login details: ' => '',
  'If more than 50 people support
// This appeal, <br>
// It will be formalized on the official form and sent by registered mail to the responsible person.' => '',
  'On {siteName} created an appeal based on {basement} "{title}" ' => '',
  'On {siteName} created based on the event {basement} "{title}" ' => '',
  'Posted collective treatment of citizens {recipient} ({department}) ' => '',
  'Your registration data in the system {siteName} ' => '',
  '{n} Sent a letter on the issue {subject} | {n} Sent letters to the problem {subject} | {n} Sent messages on the issue {subject} ' => '',
  'After the confirmation of your vote, you will be included in the list of people who voted for the importance of the topic and you will have the right to participate, with the author of the topic and other users, in editing the texts of collective letters that are formed within the framework of the issue.' => 'Després de la confirmació del seu vot, s’inclourà en el número dels usuaris que han votat per l’actualitat del tema i obtindrà el dret de participar amb l’autor del tema i els altres usuaris en la correcció dels textos de cartes col·lectives que es formen en el marc d’aquest assumpte.',
  'After the confirmation of your vote, you will be included in the list of people who voted for the importance of the topic and you will have the right to participate, with the author of the topic and other users, in editing the texts of collective letters that are formed within the framework of the petition.' => 'Després de la confirmació del seu vot, s’inclourà en el número dels usuaris que han votat per l’actualitat del tema i obtindrà del tema i obtindrà el dret de participar amb l’autor del tema i altres usuaris en la correcció dels texstos de cartes col·lectives que es formen en el marc d’aquesta solicitud.',
  'An answer received {department}' => 'Una resposta rebuda {department}',
  'Ask your friends and acquaintances to support your appeal, and then their votes will be mentioned in the official letter' => 'Demana als teus amics i coneguts que recolzin la teva solicitud, i así els seus vots es mostraràn a la carta oficial.',
  'At the moment, the appeal has collected {signsCount} signatures. If more than 50 people support this appeal, we will print on an official form and send it to the organisation in charge by registered mail.' => 'En aquest moment la sol·licitud ha reco·lectat {signsCount} firmes. Si 50 o més usuaris han votat per aquesta sol·licitud, la formalitzarem en un formulari de paper i enviarem aquest document a la organització responsable.',
  'Based on' => 'A base de',
  'If less than 50 people vote for this letter, you can put together a public appeal yourself, print it, sign it, and send it by mail. In this case, the letter will contain not only your opinion, but it will also show the votes of other citizens who voted for it.' => 'Si menys de 50 usuaris voten per aquest tema, també es pot formalitzar la carta pública, imprimir-la i enviar el document per correu. En aquest cas, la carta no només expresarà la seva opinió, sinó que mostrarà els vots d’altres ciutadans que la van recolzar.',
  'If less than 50 people vote for this subject, you can put together a public appeal yourself, print it, sign it, and send it by mail. In this case, the letter will contain not only your opinion, but it will also show the votes of other citizens who voted for it.' => 'Si menys de 50 usuaris van votar per aquest tema, també pot formalitzar la sol·licitud pública, imprimir-la i enviar el document per correu. En aquest cas la carta no només expresarà la seva opinió, sinó que mostrarà els vots d’altres ciutadans que la van recolzar.',
  'If this message was sent to you by mistake and you don`t want to support the issue in question, please just ignore this message.' => 'Si va rebre aquesta carta per equivocació i no vol recolzar aquest assumpte - només ignori aquest missatge.',
  'If this message was sent to you by mistake and you don`t want to support the petition in question, please just ignore this message.' => 'Si va rebre aquesta carta per equivocació i no vol recolzar aquesta sol·licitud - només ignori aquest missatge.',
  'Kind regards, ' => 'Atentament, ',
  'Post the information about your appeal in social networks through the automatic publication buttons on the issue’s page' => 'Publicar l’informació sobre la seva sol·licitud en xarxes socials mitjançant el botó de publicació automàtica en la pàgina del assumpte',
  'See the page of the petition' => 'Veure la pàgina de sol·licitud',
  'Subscribe to ' => 'Subscriu-te a la pàgina de ',
  'To get the maximum support, you can:' => 'Per obtenir el màxim suport, pot: ',
  'To make your vote count, please follow the link' => 'Perquè el teu vot s’accepti s’ha d’anar al enllaç',
  'You (or, maybe, someone on your behalf) have supported the petition in the system' => 'Vosté (o probablement algú de part seva) ha recolzat la sol·licitud en el sistema',
  'Your appeal' => 'La seva sol·licitud',
  'Your appeal is published on {siteName}' => 'La seva sol·licitud s’ha publicat en {siteName}',
  'an appeal has been created' => 's’ha creat una sol·licitud',
  'an event has been created' => 's’ha creat un event',
  'is published' => 's’ha publicat',
  'recommends you, first of all, to attract the support of those who is interested in solving the problem like you.' => 'et recomanem, en primer lloc, buscar el suport dels que estàn interessats en la sol·lució del problema com tu.',
);
