<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Address can not be edited and deleted, since an already formed' => '',
  'Address can not be edited, because it has supported' => '',
  'Letters' => '',
  'The city, where the organization ' => '',
  'Your passport details are pending. Please wait.' => '',
  'female' => '',
  'male' => '',
  'Are you sure you want to delete this content?' => '¿Estàs segur que vols eliminar aquest contingut?',
  'Asks' => 'Pregunta',
  'Author' => 'Creat per',
  'BUDGET' => 'PRESSUPOST',
  'Budget' => 'Pressupost',
  'Cancel' => 'Cancelar',
  'Citizen' => 'Ciutadà',
  'Copy' => 'Copiar',
  'Day' => 'Dia',
  'Delete' => 'Eliminar',
  'Edit' => 'Editar',
  'Event' => 'Event',
  'Guest' => 'Convidat',
  'Issue' => 'Assumpte',
  'It may be the address of your home, your workplace or your children’s school.' => 'Pot ser el seu domicili, la direcció del seu lloc de treball o de la escola dels seus fills.',
  'Link' => 'Enllaç',
  'Local' => 'Local',
  'Mark the places you care about. You’ll receive notifications about the events and the news from these places.' => 'Marqui els llocs que li interessin. Rebrà notificacions sobre els events i les notícies d’aquests llocs.',
  'Month' => 'Mes',
  'Nobody' => 'Ningú',
  'Organizator' => 'Organitzador',
  'Personal Information' => 'Dades personals',
  'Petition' => 'Peticion',
  'Poll' => 'Votació',
  'Project' => 'Projecte',
  'Registration Information' => 'Dades de registre',
  'Reports' => 'Informes',
  'TO:' => 'LA SOLICITUD ESTÀ DIRIGIDA A:',
  'What will the money be spent on?' => '¿En que es gastaràn els diners?',
  'Year' => 'Any',
  'You can`t edit the poll because people have already voted.' => 'No es permet ledició duna enquesta que conté vots',
  'You participate in the life of' => 'Participa a la vida de',
  'project on making the city better' => 'projecte de millora de la ciutat',
);
